#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BAC_Tracker.Droid.Resource", IsApplication=true)]

namespace BAC_Tracker.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_add_circle_black_24dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_settings_black_24dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000c
			public const int doneButton = 2131230732;
			
			// aapt resource value: 0x7f080003
			public const int linearlayout1 = 2131230723;
			
			// aapt resource value: 0x7f080006
			public const int linearlayout2 = 2131230726;
			
			// aapt resource value: 0x7f080009
			public const int linearlayout3 = 2131230729;
			
			// aapt resource value: 0x7f08000d
			public const int menu_settings = 2131230733;
			
			// aapt resource value: 0x7f080001
			public const int myButton = 2131230721;
			
			// aapt resource value: 0x7f08000b
			public const int pickerBodyType = 2131230731;
			
			// aapt resource value: 0x7f080005
			public const int pickerGender = 2131230725;
			
			// aapt resource value: 0x7f080008
			public const int pickerWeight = 2131230728;
			
			// aapt resource value: 0x7f080002
			public const int scrollView1 = 2131230722;
			
			// aapt resource value: 0x7f08000a
			public const int textBodyType = 2131230730;
			
			// aapt resource value: 0x7f080004
			public const int textGender = 2131230724;
			
			// aapt resource value: 0x7f080007
			public const int textWeight = 2131230727;
			
			// aapt resource value: 0x7f080000
			public const int toolbar = 2131230720;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Settings = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int toolbar = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int top_menus = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int BACTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int BACTheme_Base = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int preferences = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
